title: Zain Afzal
author: GitHub User
email: zain_afzal000@hotmail.co.uk
description: > # this means to ignore newlines until "show_exerpts:"
show_excerpts: true # set to true to show excerpts on the homepage
thene: texture
name:         Zain Shares
description:  Learn, Share, Contribute
url:          https://blogs.roarcoder.dev
# baseurl: /blog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: posts/:title/index.html
texture:
  title: Zain Afzal
  tagline: Developer Who Loves Sharing
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  zainafzal88
    linkedIn: in/zainafzal88
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed