version: 0.2

env:
  parameter-store:
    BUCKET: /codebuild/blogBucket

phases:
  install:
    commands:
        - gem install jekyll bundler jekyll-paginate jekyll-sitemap jekyll-gist sassc jekyll-seo-tag
  build:
    commands:
        - echo "******** Building Jekyll site ********"
        - jekyll build
  post_build:
    commands:
        - echo "******** Uploading to S3 ********"
        - aws s3 sync _site/ s3://$BUCKET
        - aws cloudfront create-invalidation --distribution-id E2EDN7QC8COSCJ --paths '/*'  